---
- name: Launch instance
  amazon.aws.ec2:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    id: "{{ aws_instance_id }}"
    key_name: "{{ aws_keypair }}"
    instance_type: "{{ aws_instance_type }}"
    image: "{{ aws_image }}"
    wait: no
    group: "{{ aws_security_group }}"
    count: 1
    vpc_subnet_id: "{{ aws_subnet }}"
    assign_public_ip: yes
    region: "{{ aws_region }}"
    instance_tags:
      Contact: bhinson@redhat.com
      DeleteBy: Never
      AlwaysUp: False
      Name: "{{ aws_instance_id }}"
